dist: bionic
language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.7.0-preview3
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8

gemfile:
  - gemfiles/cose_head.gemfile
  - gemfiles/openssl_head.gemfile
  - gemfiles/openssl_2_1.gemfile
  - gemfiles/openssl_2_0.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/cose_head.gemfile
    - gemfile: gemfiles/openssl_head.gemfile

addons:
  apt:
    packages:
      - libfaketime

before_install:
  - gem install bundler -v "~> 2.0"

before_script:
  - export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
  - export FAKETIME_NO_CACHE=1
